export const circle = {
  CI_MUTHIALPET: ["SHO_KALAPET", "SHO_MUTHIALPET"],
  CI_DNAGAR: ["SHO_DNAGAR", "SHO_SEDARAPET"],
  CI_METTUPALAYAM: ["SHO_METTUPALAYAM", "SHO_REDDIARPALAYAM"],
  CI_MAHE: ["SHO_MAHE", "SHO_PALLOOR"],
  CI_YANAM: ["SHO_YANAM"],
  CI_VILLIANUR: ["SHO_VILLIANUR", "SHO_MANGALAM"],
  CI_NETTAPAAKAM: ["SHO_NETTAPAKKAM", "SHO_THIRUDHUVANAI"],
  CI_THIRUKKANUR: ["SHO_THIRUKKANUR", "SHO_KATTERIKUPPAM"],
  CI_BAHOUR: ["SHO_BAHOUR", "SHO_KARAIKALAMPAKKAM"],
  CI_ARIYANKUPPAM: ["SHO_ARIYANKUPPAM", "SHO_THAVALAKUPPAM"],
};
